<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-17621-1659674086/blob/Team-Leader--Raghavi-V/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##Basic Python

In [3]:
#1. Split this String 

In [ ]:
s = "Hi there Sam!"

In [4]:
s = "Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


2. Use .format() to print the following string.
Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742
str=("The diameter of {planet} is {diameter} kilometers.")
print((str.format(planet="Earth",diameter=12742)))

The diameter of Earth is 12742 kilometers.


3. In this nest dictionary grab the word "hello"


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d.get('target',{}).get('hello')

Numpy

In [7]:
import numpy as np

4.1 Create an array of 10 zeros?


4.2 Create an array of 10 fives?

In [8]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all the even integers from 20 to 35

In [10]:
arr=np.arange(20,36,2)
print(arr)

[20 22 24 26 28 30 32 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatenate a and b

a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

Pandas
8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [14]:
pd.date_range(start='1/1/2023', end='10/02/2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]    
df = pd.DataFrame(lst,columns =['Tag','day','number']) 
print(df)

   Tag  day  number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24


# New Section